# Generated by Django 5.1.15 on 2026-06-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_merge_20260624_1417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonnote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonnote',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonnote',
            name='user',
        ),
        migrations.CreateModel(
            name='DailyTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('prs_reviewed', models.PositiveIntegerField(default=0)),
                ('quizzes_passed', models.PositiveIntegerField(default=0)),
                ('lessons_awarded', models.BooleanField(default=False)),
                ('prs_awarded', models.BooleanField(default=False)),
                ('quizzes_awarded', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='LessonBookmark',
        ),
        migrations.DeleteModel(
            name='LessonNote',
        ),
    ]
